### ISSUE TITLE
Community call: Reproducible workflows at scale with drake

### ISSUE THREAD

**Issue by maurolepore** [RMI-PACTA/resources#52]
* [Blog](https://ropensci.org/commcalls/2019-09-24/)
* [Video](https://vimeo.com/362383350)

Will Landau, September 24, 2019

Ambitious workflows in R, such as machine learning analyses, can be difficult to manage. A single round of computation can take several hours to complete, and routine updates to the code and data tend to invalidate hard-earned results. You can enhance the maintainability, hygiene, speed, scale, and reproducibility of such projects with the drake R package. drake resolves the dependency structure of your analysis pipeline, skips tasks that are already up to date, executes the rest with optional distributed computing, and organizes the output so you rarely have to think about data files. This talk demonstrates how to create and maintain a realistic machine learning project using drake-powered automation.

**Comment by jdhoffa** [comment]
Consider using https://github.com/ropensci/targets/ instead
