### ISSUE TITLE
An easy way to label and find examples across the entire organization

### ISSUE THREAD

**Issue by maurolepore** [RMI-PACTA/resources#54]
Similarly to #35, I suggest we label as "2dii-demo" any issue or pull request that may be useful for demonstration purposes.

We can then search all of GitHub with "label:2dii-demo". For example:

![image](https://user-images.githubusercontent.com/5856545/66825737-401b4900-ef21-11e9-8dbc-bff87e01e7f2.png)

--

Thanks @jhoff-2dii for motivating this post.

**Comment by jdhoffa** [comment]
Closing as this doesn't seem to be a practice we have kept up with
