### ISSUE TITLE
2dii accounts via twodii.apps@gmail.com

### ISSUE THREAD

**Issue by maurolepore** [RMI-PACTA/resources#81]
Login as twodii.apps@gmail.com (ask @maurolepore for a password) to access these organization-wide accounts:

* <https://rstudio.cloud/>   
* <http://github.com/twodii>: Login with `<password for twodii.apps@gmail.com>1`
* <https://www.shinyapps.io/> (paid subscription)
* <https://disqus.com/>
* <https://www.netlify.com/>. Examples:
    * Site: https://r2dii-demo-blog.netlify.com/
    * Source: https://github.com/2DegreesInvesting/r2dii-demo-blog
    * Disqus: https://disqus.com/home/forums/r2dii-demo-blog/

**Comment by maurolepore** [comment]
Relates to #12

**Comment by jdhoffa** [comment]
Closing as no longer relevant here.
